import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import bgImage from "@/assets/images/header_bg.png";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-col min-h-screen justify-between`}
        style={{
          backgroundImage: `url(${bgImage.src})`,
          backgroundRepeat: "no-repeat"
        }}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
